sudo: false
language: java
jdk: oraclejdk7

install:
- mkdir -m 700 -p -v $HOME/.ssh
- ssh-keygen -t rsa -N '' -f $HOME/.ssh/id_rsa
- cat $HOME/.ssh/id_rsa.pub > $HOME/.ssh/authorized_keys
- ssh -o StrictHostKeyChecking=no -o HostKeyAlgorithms=ssh-rsa -o UserKnownHostsFile=$HOME/.ssh/known_hosts -i $HOME/.ssh/id_rsa localhost id
- ssh-keygen -H -F localhost
 

script:
- ./gradlew check install

- cd acceptance-test
- ../gradlew --version
- ../gradlew -s -Pversion=SNAPSHOT test

- sed -i -e 's,gradle-[0-9.]*-,gradle-1.12-,g' ../gradle/wrapper/gradle-wrapper.properties
- ../gradlew --version
- ../gradlew -s -Pversion=SNAPSHOT test


after_success:
- test ${TRAVIS_TAG} && ./gradlew bintrayUpload

env:
  global:
  - TERM=dumb
  - secure: O1woxzaGDbP7FjbnfCryVwfjOqqTU8Ix7dieAdOSwdfLS21RxV5vBdk7rgep+Gpgj0bhMILHpnlmuH6oh5oLNykQL2DKhC4atjyWjTZBVKMBvDabPDKXrsT8pvexYzwTUlMACcEU8/iBvNjqJjkJzQy1TuIrknqXp4GdTzlyyko=
  - secure: hUWvSso9YoE9v1FDiJUzsURae4dpNFK5J59UqeKqyD17Mz4tefZtTzMcsbx9qe+6Y7VT6RsH/MAryosJz53OzDQQX0NBWWNsCpxNU97/cSbmw2Tl3523pKc5irjbv43+vFF5kSya16AmRcAAymbAzpNnvKDFujXONRYbnhYRYV8=
