sudo: false
language: java
jdk: oraclejdk7

env:
- JAVA_OPTS="-Xmx1024m -Xms1024m"

install:
- mkdir -m 700 -p -v $HOME/.ssh
- echo '-----BEGIN RSA PRIVATE KEY-----'        >> "$HOME/.ssh/id_ext"
- echo "$EXT_SSH_KEY" | fold -w 76              >> "$HOME/.ssh/id_ext"
- echo '-----END RSA PRIVATE KEY-----'          >> "$HOME/.ssh/id_ext"
- chmod -v 600 "$HOME/.ssh/id_ext"
- unset EXT_SSH_KEY

- ./acceptance-test/setup-external-ssh.sh


script:
- ./gradlew check


after_success:
- test ${TRAVIS_TAG} && ./gradlew bintrayUpload
